print("Once, there was a _______...")
user_input1 = input("noun:")
print("Once, there was a " + user_input1 + " whose dream in life was _______")
user_input2 = input("verb:")
print("Once, there was a " + user_input1 + " whose dream in life was " + user_input2 + ". Everyone told _____")
user_input3 = input("pronoun:")
print("Everyone told " + user_input3 + " that _____")
user_input4 = input("noun:")
print("Everyone told " + user_input3 + " that " + user_input4 + " can't _____")
user_input5 = input("verb:")
print("Everyone told " + user_input3 + " that " + user_input4 + " can't " + user_input5 + ", but _____")
user_input6 = input("noun:")
print("Everyone told " + user_input3 + " that " + user_input4 + " can't " + user_input5 + ", but " + user_input6 + " was _____")
user_input7 = input("adjective:")
print("Everyone told " + user_input3 + " that " + user_input4 + " can't " + user_input5 + ", but " + user_input6 + " was " + user_input7 + ". First, he went to _____")
user_input8 = input("noun:")
print("First, he went to " + user_input8 + ". There, he _____")
user_input9 = input("verb:")
print("There, he " + user_input9 + ", but that just made everyone _____")
user_input10 = input("adjective:")
print("There, he " + user_input9 + ", but that just made everyone " + user_input10 + ". From there, he made the long trip to _____")
user_input11 = input("noun:")
print("From there, he made the long trip to " + user_input11 + ", where to his surpirse, he discovered _____")
user_input12 = input("noun:")
print("From there, he made the long trip to " + user_input11 + ", where to his surpirse, he discovered " + user_input12 + ". Feeling _____")
user_input13 = input("adjective:")
print("Feeling " + user_input13 + ", he went back home, bringing with him a _____")
user_input14 = input("noun:")
print("Feeling " + user_input13 + ", he went back home, bringing with him a " + user_input14 + ".")
user_input15 = input("Finish?:")
print("Once, there was a " + user_input1 + " whose dream in life was " + user_input2 + ". Everyone told " + user_input3 + " that " + user_input4 + " can't " + user_input5 + ", but " + user_input6 + " was " + user_input7 + ". First, he went to " + user_input8 + ". There, he " + user_input9 + ", but that just made everyone " + user_input10 + ". From there, he made the long trip to " + user_input11 + ", where to his surpirse, he discovered " + user_input12 + ". Feeling " + user_input13 + ", he went back home, bringing with him a " + user_input14 + ".")